# -*- coding: utf-8 -*-
# Generated by Django 1.10b1 on 2016-07-23 13:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('date', models.DateTimeField(verbose_name='Date')),
                ('number_of_hours', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=10)),
                ('employee_id', models.IntegerField()),
                ('is_submited', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(verbose_name='Date')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='overtime.Report'),
        ),
    ]
